# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
PROJECT_DIR       = ./
USER_LIB_PATH    =  ../lib/
BOARD_TAG    = pro328
# BOARD_TAG    = pro
# BOARD_TAG    = 8MHzatmega328
# ARDUINO_LIBS += TinyGPS	
# GPS pin Affichage


#MONITOR_PORT = /dev/ttyUSB0
#MONITOR_BAUDRATE  = 115200
include /usr/share/Arduino-Makefile/Arduino.mk